name: 'Github Events To Lark Bot Action'
description: 'send message to lark bot'
author: 'mobius-ring'
branding:
  icon: 'cloud-snow'
  color: 'blue'
inputs:
  webhook:
    description: 'lark bot webhook url'
    required: true
  signkey:
    description: 'set when you enable signature verify'
    required: false
outputs:
  code:
    description: 'code from response'
runs:
  using: 'node20'
  main: 'dist/index.js'
